kind: Deployment
apiVersion: apps/v1
metadata:
  name: firstdotnet
  namespace: default
  generation: 2
  labels:
    k8s-app: firstdotnet
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: firstdotnet
  template:
    metadata:
      name: firstdotnet
      creationTimestamp: null
      labels:
        k8s-app: firstdotnet
    spec:
      containers:
        - name: firstdotnet
          image: 'localhost:5000/lichutinmodul/firstdotnet'
          readinessProbe: # способно ли приложение сейчас обрабатывать запросы
            httpGet:
              path: /readness/check
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:  # живо ли приложение в принципе
            httpGet:
              path: /liveness/check
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: REMOTE_ENDPOINT
            value: "http://generator:8080"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: generator
  namespace: default
  generation: 2
  labels:
    run: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: generator
  template:
    metadata:
      name: generator
      creationTimestamp: null
      labels:
        run: generator
    spec:
      containers:
        - name: generator
          image: 'localhost:5000/lichutinmodul/generator'
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: generator
  labels:
    run: generator
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: generator